---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - cp index.html $DEPLOYPATH
    - cp styles.css $DEPLOYPATH
    - cp -r photos $DEPLOYPATH
    - cp -r elements $DEPLOYPATH
    - cp -r styles $DEPLOYPATH
