---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R images $DEPLOYPATH 
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R elements $DEPLOYPATH
